// dsh-voice-capture 0.3.2 unit tests U1–U10 (results/harness-microphone-ui-20260915/PLAN_0.3.2.md).
// Fixtures: capability entries generated by the FROZEN host 0.4.6 (`9d1c20b6…`, TASK_CONTRACT §K.11 optionControls) from
// catalog checkpoint 0550 adapter_models entries (`d697e66f…`), and by the FROZEN host 0.4.5 from checkpoint 0515 (raw
// requestOptions strings only, no optionControls) as the negative control.
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { CapabilityModel } from '../src/client/audio/api.ts'
import { LiveController, liveInputName } from '../src/client/audio/live.ts'
import { offerFor, optionFacts, rendersControl } from '../src/client/audio/options.ts'
import { parseAudioResults, parseResultDocument } from '../src/client/audio/results.ts'
import { resultLinks } from '../src/client/audio/recordings.ts'
import { TaskInputsController } from '../src/client/audio/task-controller.ts'
import { missingInputs, offerOf, taskView } from '../src/client/audio/tasks.ts'
import type { CaptureBackend, CaptureOpenOptions } from '../src/client/capture.ts'

type Fixture = { source: { host: string; adapterModelsSha256: string }; doc: { routes: { models: CapabilityModel[] }[] } }
const load = (name: string) => JSON.parse(readFileSync(new URL(name, import.meta.url), 'utf8')) as Fixture
const H046 = load('./fixtures-host046-catalog0550.json')
const H045 = load('./fixtures-host045-catalog0515.json')
const hostEntry = (id: string) => H046.doc.routes[0]!.models.find(m => m.id === id)!
const host045Entry = (id: string) => H045.doc.routes[0]!.models.find(m => m.id === id)!
const S = 'session-032' as SessionId
const offers = (model: CapabilityModel) => {
  const view = taskView(model)
  return Object.fromEntries(view.params.map(p => [p.key, offerOf(view, p)]))
}

test('U1 host 0.4.6 option controls drive the form: required, conditional, restricted, not verified, negatives, unlisted', () => {
  assert.equal(H046.source.host, 'dsh-dgx-audio 0.4.6')
  assert.equal(H046.source.adapterModelsSha256, 'd697e66f13d03046da36dc238818ec2b85505c5248315c98378233efeda58a54')
  const design = offers(hostEntry('qwen3-tts-12hz-1-7b-voicedesign-speech'))
  assert.equal(design.instructions, 'required')
  assert.equal(design.taskType, 'required')
  assert.equal(design.speed, 'offered-unverified')
  assert.equal(design.voice, 'unlisted', 'the VoiceDesign variant does not list voice: hidden, never "unsupported"')
  const base = taskView(hostEntry('qwen3-tts-12hz-1-7b-base-speech'))
  assert.equal(base.options.source, 'option-controls')
  assert.match(base.options.scope!, /scoped to this variant/)
  assert.equal(base.options.byKey.refText!.mandatory, 'conditional')
  assert.deepEqual(base.options.byKey.refText!.conditions, ['ref_text (required unless x_vector_only_mode)'])
  assert.equal(base.input.referenceAudio, 'required', 'host io (deployment refAudio attachment) with an active control')
  assert.deepEqual(base.options.notSendable.map(n => n.option), ['speaker_embedding'])
  const index = taskView(hostEntry('indextts-2-speech'))
  assert.equal(index.options.byKey.refText!.obligation, 'ignored')
  assert.equal(index.input.referenceText, 'none', 'an ignored ref_text is not asked for')
  assert.equal(offerOf(index, index.params.find(p => p.key === 'instructions')!), 'not-offered')
  assert.equal(index.options.byKey.referenceAudio!.mandatory, 'conditional')
  assert.equal(index.input.emotionAudio, 'optional', 'active emotionAudio control')
  assert.equal(taskView(hostEntry('moss-ttsd-v1-0-speech-dialogue')).input.referenceAudio2, 'optional')
  assert.equal(taskView(hostEntry('moss-ttsd-v1-0-speech')).input.referenceAudio2, 'none', 'same family without ref_audio_2 in its map')
  const dots = taskView(hostEntry('dots-tts-soar-speech'))
  const voice = dots.params.find(p => p.key === 'voice')!
  assert.equal(offerOf(dots, voice), 'offered-restricted')
  assert.ok(dots.options.byKey.voice!.restriction!.length > 0)
  assert.deepEqual(dots.options.byKey.voice!.conditions, ['voice other than default'])
  assert.equal(offerOf(dots, dots.params.find(p => p.key === 'sampleRate')!), 'not-offered')
  const breeze = offers(hostEntry('breeze-tts-2-speech-clone-ws'))
  assert.deepEqual([breeze.xVectorOnlyMode, breeze.language, breeze.speed], ['not-offered', 'not-offered', 'not-offered'], 'rejected and value-conditional rejections are never relaxed')
  assert.equal(breeze.refText, 'required')
})

test('U2 no control comes from request option strings, legacy io, an inactive or unrecognized obligation', () => {
  // Host 0.4.5 publishes the raw strings (and io derived from them) but no optionControls: everything catalog-side is unknown.
  const legacy = taskView(host045Entry('qwen3-tts-12hz-1-7b-customvoice-speech'))
  assert.equal(legacy.options.source, 'none')
  assert.equal(offerOf(legacy, legacy.params.find(p => p.key === 'speed')!), 'unknown', '"speed (not with streaming)" is listed in the strings')
  assert.equal(offerOf(legacy, legacy.params.find(p => p.key === 'voice')!), 'offered-configured', 'deployment default only')
  const legacyDialogue = host045Entry('moss-ttsd-v1-0-speech-dialogue') as CapabilityModel & { io?: { input?: Record<string, unknown> } }
  assert.equal(legacyDialogue.io?.input?.referenceAudio2, 'optional', 'host 0.4.5 io read the strings')
  assert.equal(taskView(legacyDialogue).input.referenceAudio2, 'none', 'that io alone never enables the slot')
  const control = (c: Record<string, unknown>) => optionFacts({ optionControls: { contract: 'dsh-audio/option-controls@1', basis: 'catalog-map', controls: [{ key: 'seed', wireKey: 'seed', kind: 'param', mandatory: false, entries: [], conditions: [], ...c }], blockers: [], notSendable: [], unmapped: [], hostOptions: [], inputErrors: [] } })
  assert.equal(offerFor(control({ obligation: 'rejected', active: true }), 'seed', true, true), 'not-offered', 'active=true never overrides a negative')
  assert.equal(offerFor(control({ obligation: 'supported-maybe', active: true }), 'seed', true, true), 'unknown', 'unrecognized obligation')
  assert.equal(offerFor(control({ obligation: 'offer-unverified', active: false }), 'seed', true, true), 'unknown')
  assert.equal(offerFor(control({ obligation: 'offer-unverified', active: true }), 'speed', true, true), 'unknown', 'a key without a control')
  assert.equal(offerFor(optionFacts({ optionControls: { contract: 'dsh-audio/option-controls@2', controls: [] } }), 'seed', true, false), 'offered-configured', 'another contract version is not read')
  const empty = optionFacts({ optionControls: { contract: 'dsh-audio/option-controls@1', basis: 'catalog-map-empty', controls: [{ key: 'voice', obligation: 'unknown', active: false, mandatory: false, reason: 'empty-map' }], inputErrors: [{ field: 'requestOptionsEvidence', message: 'over 16384 characters' }] } })
  assert.deepEqual([empty.basis, offerFor(empty, 'voice', true, true), empty.inputErrors[0]!.field], ['catalog-map-empty', 'unknown', 'requestOptionsEvidence'])
  assert.equal(rendersControl('unknown') || rendersControl('unlisted') || rendersControl('not-offered'), false)
})

test('U3 required controls block the request until filled; blockers name what this host cannot send', () => {
  const view = taskView(hostEntry('qwen3-tts-12hz-1-7b-voicedesign-speech'))
  const draft = { text: 'Hello', hasAudio: false, hasReference: false, referenceConsent: false, referenceText: '' }
  assert.deepEqual(missingInputs(view, { ...draft, requiredOptionsMissing: ['instructions'] }), ['requiredOption'])
  assert.deepEqual(missingInputs(view, { ...draft, requiredOptionsMissing: [] }), [])
  const base = taskView(hostEntry('qwen3-tts-12hz-1-7b-base-speech'))
  assert.deepEqual(missingInputs(base, { ...draft, hasReference: false }), ['referenceAudio'])
  const ws = taskView(hostEntry('indextts-2-speech-ws'))
  assert.deepEqual(ws.options.blockers.map(b => [b.wireKey, b.status, b.reason]), [['ref_audio', 'required-conditional', 'needs deployment realtime.refAudioFile']])
  assert.match(ws.options.blockers[0]!.raw!, /^ref_audio/)
  assert.deepEqual([ws.input.referenceAudio, ws.input.emotionAudio, ws.input.referenceAudio2], ['none', 'none', 'none'], 'WS: clips are deployment files or not sendable')
  const video = taskView(hostEntry('minimax-h3-video'))
  assert.deepEqual(video.options.blockers.map(b => b.option), ['short_edge'])
})

class NoCapture implements CaptureBackend {
  support() { return undefined }
  async listDevices() { return [] }
  onDeviceChange() { return () => {} }
  async open(options: CaptureOpenOptions) { return { sampleRate: options.sampleRate ?? 16000, deviceLabel: 'fixture', deviceId: '', close: async () => {} } }
}

function host(reply: (body: Record<string, unknown>) => Record<string, unknown>, openExtra: Record<string, unknown> = {}) {
  const calls: { path: string; body: Record<string, unknown> }[] = []
  const fetchImpl = async (url: string, init?: RequestInit) => {
    const path = new URL(url).pathname.replace('/api/dsh-dgx-audio/v1/', '')
    const body = typeof init?.body === 'string' ? JSON.parse(init.body) as Record<string, unknown> : {}
    calls.push({ path, body })
    if (path === 'live/open') return new Response(JSON.stringify({ ok: true, liveId: 'L', task: 'duplex', input: { encoding: 'pcm_s16le', sampleRate: 16000, channels: 1, frameMs: 200, maxFrameBytes: 64000 }, ...openExtra }))
    if (path === 'live/control' && body.type !== 'commit' && body.type !== 'playback-ack') return new Response(JSON.stringify({ ok: true, ...reply(body) }))
    const result = reply(body)
    if (typeof result.status === 'number') return new Response(JSON.stringify(result.body), { status: result.status })
    return new Response(JSON.stringify({ ok: true, ...result }))
  }
  return { calls, fetchImpl }
}

test('U4 Interrupt outcomes: no-op outcomes never read as interrupted; cancelled needs the matching cancelled response', async () => {
  const outcomes: Record<string, unknown>[] = []
  let next: Record<string, unknown> = { controlId: 'c1', sent: false, targetResponseId: null, outcome: 'no-active-response' }
  const h = host(() => next)
  const live = new LiveController(new NoCapture(), h.fetchImpl, () => false, async () => ({ ok: true }), () => 0)
  await live.start(S, { provider: 'p', model: 'm' }, 'declared', false)
  await live.control('barge-in')
  outcomes.push(live.source.getSnapshot().control!)
  assert.deepEqual([live.source.getSnapshot().control!.outcome, live.source.getSnapshot().control!.confirmed], ['no-active-response', false])
  live.handleEvent({ type: 'live.response', liveId: 'L', responseId: 'r1', status: 'created' })
  next = { controlId: 'c2', sent: true, targetResponseId: 'r1', outcome: 'pending' }
  await live.control('barge-in')
  assert.equal(h.calls.at(-1)!.body.responseId, 'r1', 'targets the active response of this liveId')
  assert.equal(live.source.getSnapshot().control!.outcome, 'pending')
  live.handleEvent({ type: 'live.control.result', liveId: 'OTHER', controlId: 'c2', outcome: 'cancelled', targetResponseId: 'r1' })
  assert.equal(live.source.getSnapshot().control!.outcome, 'pending', 'another connection is ignored')
  live.handleEvent({ type: 'live.control.result', liveId: 'L', controlId: 'c2', control: 'barge-in', sent: true, targetResponseId: 'r1', outcome: 'cancelled' })
  assert.deepEqual([live.source.getSnapshot().control!.outcome, live.source.getSnapshot().control!.confirmed], ['cancelled', false], 'no cancelled response yet')
  live.handleEvent({ type: 'live.response', liveId: 'L', responseId: 'r1', status: 'cancelled', reason: 'client_force_barge_in' })
  assert.equal(live.source.getSnapshot().control!.confirmed, true)
  live.handleEvent({ type: 'live.response', liveId: 'L', responseId: 'r2', status: 'created' })
  next = { controlId: 'c3', sent: true, targetResponseId: 'r2', outcome: 'pending' }
  await live.control('cancel-response')
  live.handleEvent({ type: 'live.control.result', liveId: 'L', controlId: 'c3', outcome: 'response-already-completed', targetResponseId: 'r2' })
  assert.deepEqual([live.source.getSnapshot().control!.outcome, live.source.getSnapshot().control!.confirmed], ['response-already-completed', false])
  for (const outcome of ['stale', 'unconfirmed', 'response-not-active']) {
    next = { controlId: `c-${outcome}`, sent: outcome !== 'response-not-active', targetResponseId: 'r2', outcome }
    await live.control('barge-in')
    assert.deepEqual([live.source.getSnapshot().control!.outcome, live.source.getSnapshot().control!.confirmed], [outcome, false])
  }
  next = {}
  await live.control('barge-in')
  assert.equal(live.source.getSnapshot().control!.outcome, 'no-outcome', 'hosts before 0.4.5 report no outcome')
  assert.equal(live.source.getSnapshot().phase, 'live', 'a control outcome never ends the session')
  await live.dispose()
})

test('U4b results of other controls never change an Interrupt whose reply is still in flight (E2E finding 06:17)', async () => {
  let release!: () => void
  const held = new Promise<void>((resolve) => { release = resolve })
  const h = host(body => (body.type === 'barge-in' ? { controlId: 'c9', sent: false, targetResponseId: null, outcome: 'no-active-response' } : {}))
  const slow = async (url: string, init?: RequestInit) => {
    if (String(init?.body ?? '').includes('"barge-in"')) await held
    return h.fetchImpl(url, init)
  }
  const live = new LiveController(new NoCapture(), slow, () => false, async () => ({ ok: true }), () => 0)
  await live.start(S, { provider: 'p', model: 'm' }, 'declared', false)
  live.handleEvent({ type: 'live.response', liveId: 'L', responseId: 'r1', status: 'created' })
  const pending = live.control('barge-in')
  await new Promise(resolve => setTimeout(resolve, 5))
  for (const event of [
    { control: 'playback-ack', controlId: 'c7', targetResponseId: 'r1', outcome: 'acknowledged' },
    { control: 'commit', controlId: 'c8', targetResponseId: null, outcome: 'committed' },
    { control: 'barge-in', controlId: 'c1', targetResponseId: 'r0', outcome: 'cancelled' },
  ]) {
    live.handleEvent({ type: 'live.control.result', liveId: 'L', sent: true, ...event })
    assert.equal(live.source.getSnapshot().control!.outcome, 'pending', `${event.control} ${event.controlId}`)
  }
  release()
  await pending
  assert.deepEqual([live.source.getSnapshot().control!.outcome, live.source.getSnapshot().control!.confirmed], ['no-active-response', false])
  await live.dispose()
})

test('U5 per-connection observations and input integrity', async () => {
  const h = host(body => (body.type === undefined ? { input: null, inputIntegrity: { framesForwarded: 12, serverRejectedAppends: 2, rejections: [] } } : {}))
  const live = new LiveController(new NoCapture(), h.fetchImpl, () => false, async () => ({ ok: true }), () => 0)
  await live.start(S, { provider: 'p', model: 'm' }, 'declared', false, 'conversation')
  live.handleEvent({ type: 'live.capability', liveId: 'OTHER', key: 'bargeIn', state: 'verified' })
  live.handleEvent({ type: 'live.capability', liveId: 'L', key: 'fullDuplex', state: 'advertised', implementationLevel: 'model_native_duplex', at: 't' })
  live.handleEvent({ type: 'live.input.rejected', liveId: 'L', code: 'invalid_audio', message: 'bad frame', lastForwardedSeq: 3 })
  const snap = live.source.getSnapshot()
  assert.deepEqual(Object.keys(snap.observed), ['fullDuplex'])
  assert.equal(snap.observed.fullDuplex!.implementationLevel, 'model_native_duplex')
  assert.equal(snap.inputRejected, 1)
  await live.endInput()
  await live.close()
  assert.deepEqual(live.source.getSnapshot().integrity, { framesForwarded: 12, serverRejectedAppends: 2 })
})

test('U6 streamed TTS: params go with the first text of an utterance, 409 is a notice, live.words is kept per sentence', async () => {
  let refuse = false
  const h = host((body) => {
    if (refuse && body.params !== undefined) return { status: 409, body: { ok: false, error: { code: 'UTTERANCE_IN_PROGRESS', message: 'params only before the first text' } } }
    return { chunks: 1, utterance: 0 }
  }, { task: 'tts.stream-input', input: { encoding: 'text', route: '/api/dsh-dgx-audio/v1/live/text' } })
  const live = new LiveController(new NoCapture(), h.fetchImpl, () => false, async () => ({ ok: true }), () => 0)
  await live.start(S, { provider: 'p', model: 'ws' }, 'declared', false, 'text-input')
  assert.equal(await live.sendText('Hello. ', false, { speed: 1.2, wordTimestamps: true }, false), true)
  assert.deepEqual(h.calls.at(-1)!.body, { text: 'Hello. ', params: { speed: 1.2, wordTimestamps: true } })
  assert.equal(await live.sendText('More.', false, { speed: 1.5 }, false), true)
  assert.deepEqual(h.calls.at(-1)!.body, { text: 'More.' }, 'no params inside an open utterance')
  assert.equal(await live.sendText('', true, undefined, false), true)
  assert.equal(live.source.getSnapshot().utteranceOpen, false)
  assert.equal(live.source.getSnapshot().phase, 'live', 'ending an utterance keeps the session open')
  assert.equal(await live.sendText('Second.', false, { speed: 1.5 }, false), true)
  assert.deepEqual(h.calls.at(-1)!.body, { text: 'Second.', params: { speed: 1.5 } })
  await live.sendText('', true, undefined, false)
  refuse = true
  assert.equal(await live.sendText('Third.', false, { speed: 2 }, false), false)
  assert.deepEqual([live.source.getSnapshot().textParams!.state, live.source.getSnapshot().textParams!.code, live.source.getSnapshot().phase], ['rejected', 'UTTERANCE_IN_PROGRESS', 'live'])
  live.handleEvent({ type: 'live.words', liveId: 'L', responseId: 'utt-0', sentenceIndex: 0, state: 'aligned', words: [{ word: 'Hello', startMs: 0, endMs: 300 }] })
  live.handleEvent({ type: 'live.words', liveId: 'L', responseId: 'utt-0', sentenceIndex: 1, state: 'silence', words: [] })
  assert.deepEqual(live.source.getSnapshot().words.map(w => [w.sentenceIndex, w.state, w.words.length]), [[0, 'aligned', 1], [1, 'silence', 0]])
  await live.endInput()
  assert.equal(live.source.getSnapshot().phase, 'awaiting')
  await live.dispose()
})

test('U7 video: reference slots from active controls, result with sound-track facts', async () => {
  const view = taskView(hostEntry('wan2-2-s2v-14b-video'))
  assert.deepEqual([view.task, view.output.video, view.input.imageReference, view.input.audioReference, view.input.audio, view.speaks], ['video-generation', true, 'optional', 'required', 'none', false], 'audio reference: active control + host params_required')
  const cosmos = taskView(hostEntry('cosmos3-nano-video'))
  assert.deepEqual([cosmos.input.imageReference, cosmos.input.audioReference], ['none', 'none'], 'io image "optional" without an active control is no slot')
  const [result] = parseAudioResults('```dsh-audio-result\n' + JSON.stringify({
    v: 1, task: 'video-generation', outputs: [
      { kind: 'video', role: 'video', recordingId: 'rec_v1', sha256: 'a'.repeat(64), bytes: 1000, width: 640, height: 360, durationSeconds: 2, delivery: 'final-only', audioTrack: { present: true, codec: 'mp4a', sampleRate: 48000, channels: 2, durationSeconds: 2, sha256: 'b'.repeat(64) } },
      { kind: 'video', role: 'video', recordingId: 'rec_v2', audioTrack: { present: false } },
    ],
  }) + '\n```', 7)
  assert.deepEqual(result!.outputs.map(o => [o.kind, o.width, o.audioTrack?.present, o.audioTrack?.codec]), [['video', 640, true, 'mp4a'], ['video', undefined, false, undefined]])
  const uploads: string[] = []
  const controller = new TaskInputsController({ async upload(_s, data, name) { uploads.push(`${name}:${data.type}`); return { ok: true, value: { receiptId: `r${uploads.length}`, file: { attachmentId: 'a', name, bytes: data.size } } } as never } }, { binding: () => ({ session: { beginSubmission: () => ({ requestId: 'q' as never, abandon: () => {} }), prompt: async () => ({ ok: true, value: { accepted: true } }) as never } }) })
  controller.setReference(S, new Blob([new Uint8Array(8)], { type: 'image/png' }), 'file', 'still.png', 'imageReference')
  controller.setReference(S, new Blob([new Uint8Array(8)], { type: 'text/plain' }), 'file', 'x.txt', 'imageReference')
  assert.equal(controller.source(S).getSnapshot().error?.code, 'reference-type')
  controller.dismissError(S)
  controller.setConsent(S, true, 'imageReference')
  controller.setReference(S, new Blob([new Uint8Array(8)], { type: 'audio/wav' }), 'file', 'voice.wav', 'audioReference')
  controller.setConsent(S, true, 'audioReference')
  const block = JSON.parse(controller.extras(S, 'wan2-2-s2v-14b-video', view).block!.split('\n')[1]!) as Record<string, string>
  assert.match(block.imageReference!, /^image-reference-\d{8}-\d{6}\.png$/)
  assert.match(block.audioReference!, /^audio-reference-\d{8}-\d{6}\.wav$/)
  assert.equal(await controller.generate(S, 'wan2-2-s2v-14b-video', view, 'A lighthouse keeper speaking'), true)
  assert.deepEqual(uploads.map(u => u.split(':')[1]), ['image/png', 'audio/wav'])
  controller.dispose()
})

test('U8 result link line with a res_ id resolves to the stored result document', () => {
  const text = 'Speech generated.\n- [🧾 tts result](/api/dsh-dgx-audio/v1/result?id=res_0123456789abcdef_x-y)'
  assert.deepEqual(resultLinks(text, 9), [{ seq: 9, resultId: 'res_0123456789abcdef_x-y', label: '🧾 tts result' }])
  const doc = parseResultDocument({ v: 1, task: 'tts-stream', resultId: 'res_0123456789abcdef_x-y', origin: 'live-replay', input: { kind: 'text' }, outputs: [{ kind: 'audio', role: 'speech', recordingId: 'rec_1', delivery: 'progressive' }], wordTimestamps: { state: 'aligned', words: [{ word: 'Hi', startMs: 0, endMs: 200 }] } }, 9)
  assert.equal(doc!.resultId, 'res_0123456789abcdef_x-y')
  assert.equal(doc!.outputs[0]!.delivery, 'progressive')
  assert.equal(doc!.wordTimestamps!.words.length, 1)
})

test('U9 alignment task: audio plus reference transcript, words result, no speech', () => {
  const view = taskView(hostEntry('qwen3-forcedaligner-0-6b-align'))
  assert.deepEqual([view.task, view.input.text, view.input.audio, view.speaks, view.output.audio], ['alignment', 'required', 'required', false, false])
  assert.deepEqual(missingInputs(view, { text: '', hasAudio: false, hasReference: false, referenceConsent: false, referenceText: '' }), ['text', 'audio'])
})

test('U10 word timestamps and WS differences: final-header on HTTP, unlisted on the speech WS variant, not-sendable keys named', () => {
  const http = taskView(hostEntry('qwen3-tts-12hz-1-7b-customvoice-speech-word-timestamps'))
  assert.deepEqual([offers(hostEntry('qwen3-tts-12hz-1-7b-customvoice-speech-word-timestamps')).wordTimestamps, http.options.byKey.wordTimestamps!.delivery, http.output.wordTimestamps], ['offered-unverified', 'final-header', true])
  const ws = taskView(hostEntry('qwen3-tts-12hz-1-7b-customvoice-speech-ws'))
  assert.equal(ws.live, 'text-input')
  assert.deepEqual([offers(hostEntry('qwen3-tts-12hz-1-7b-customvoice-speech-ws')).wordTimestamps, ws.options.byKey.wordTimestamps!.delivery], ['unlisted', 'live.words'])
  assert.equal(offers(hostEntry('qwen3-tts-12hz-1-7b-customvoice-speech-ws')).speed, 'offered-unverified')
  assert.deepEqual(ws.options.notSendable.map(n => [n.option, n.reason]), [['sample_rate', 'not in the server session config']])
  assert.equal(taskView(hostEntry('qwen3-forcedaligner-0-6b-align')).params.filter(p => rendersControl(offerOf(taskView(hostEntry('qwen3-forcedaligner-0-6b-align')), p))).length, 0)
})

test('U6b streamed TTS text receipt (host 0.4.6 close input kind text, no recordingId) is named and logged (E2E finding 06:23)', () => {
  const text = { kind: 'text' as const, name: 'live-text-b993402260bf.txt', bytes: 52, sha256: '4e308fb5a1af39240139a3a229c24f4811dc4212196a1ddc68e5a7ee8ae328e9', receiptId: 'd2ce', attachmentId: 'sha256:4e30' }
  assert.equal(liveInputName(text), 'live-text-b993402260bf.txt')
  assert.equal(liveInputName({ ...text, name: undefined }), 'live-text-4e308fb5a1af.txt')
  assert.equal(liveInputName({ recordingId: 'rec_0123456789abcdef', bytes: 10, sha256: 'f'.repeat(64) }), 'live-input-456789abcdef.wav')
})
