// 0.4.2: I3-VOX chat/audio system placement, pending-turn parsing after a Harness model switch, catalog `wire`
// alias, per-turn speech fields of existing endpoints, and speech-stream per-chunk sample rates. Mock transport only.
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { test } from 'node:test'
import { createUserMessage, fileHandleText } from '@deepseek-ai/dsh-llm'

import { createAudioPlugin } from '../src/index.js'
import { resolveConfig } from '../src/config.js'
import { wavHeader } from '../src/pcm.js'
import { collect, fakeStore, pcm16, scriptedServer, sleep, tempDir, wav } from './helpers/fixtures.js'
import { wsServer } from './helpers/ws-server.js'

const text = t => ({ type: 'text', text: t })
const user = (...blocks) => ({ role: 'user', content: blocks.map(b => (typeof b === 'string' ? text(b) : b)) })
const optionsBlock = obj => `\`\`\`dsh-audio-options\n${JSON.stringify(obj)}\n\`\`\``
// Exactly what dsh-agent model-selection appends after the prompt on the first request after a switch.
const modelChanged = (from, to) => createUserMessage({
  content: [text(`[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`)],
  source: { kind: 'plugin', plugin: 'model-selection', form: 'notice', summary: { text: `${from} → ${to}` } },
})
// The I3-VOX server error (vLLM 0.29.0, Voxtral Mini 3B 2507), verbatim.
const VOXTRAL_400 = 'Found system messages at indexes [0] and audio chunks in messages at indexes [1]. This is not allowed prior to the tokenizer version 13.'

async function multiStore(files) {
  const stores = await Promise.all(files.map(([bytes, name]) => fakeStore(bytes, name)))
  const byName = n => stores.find(s => s.ref.name === n)
  return {
    refs: stores.map(s => s.ref),
    handle: n => text(fileHandleText(byName(n).ref, byName(n).path)),
    store: { fileHostPath: r => byName(r.name).path, async * readFileStream(r) { yield * byName(r.name).store.readFileStream(r) } },
  }
}

async function plugin(routes, store) {
  const outputDir = await tempDir('dgx-042-')
  const p = createAudioPlugin({ rowConfig: { outputDir, hubLimits: { pingMs: 60_000 }, routes }, log: () => {}, attachments: () => store })
  const readLog = async () => (await readFile(p.config().invocationLog, 'utf8')).trim().split('\n').map(l => JSON.parse(l))
  return { p, readLog }
}

/** Chat server that rejects a system message together with audio, like vLLM's Mistral tokenizer mode (< v13). */
function mistralLikeChat() {
  return scriptedServer(async (req, res, call) => {
    const messages = call.json.messages
    const hasAudio = messages.some(m => Array.isArray(m.content) && m.content.some(p => p.type === 'input_audio'))
    if (hasAudio && messages.some(m => m.role === 'system')) {
      res.writeHead(400, { 'content-type': 'application/json' })
      res.end(JSON.stringify({ error: { message: VOXTRAL_400, type: 'BadRequestError', code: 400 } }))
      return
    }
    res.writeHead(200, { 'content-type': 'application/json' })
    res.end(JSON.stringify({ choices: [{ index: 0, message: { content: 'The speaker asks the audience what they can do for their country.' }, finish_reason: 'stop' }] }))
  })
}

test('I3-VOX c3: Voxtral-Mini-3B-2507 chat with audio folds the system prompt by verified rule (product default path)', async (tc) => {
  const server = await mistralLikeChat()
  tc.after(() => server.close())
  const fx = await multiStore([[wav(0.5), 'jfk.wav']])
  const { p, readLog } = await plugin([{ provider: 'vox', displayName: 'Voxtral', baseURL: server.url, models: [{ id: 'voxtral-chat', upstreamModel: 'mistralai/Voxtral-Mini-3B-2507', streaming: { text: 'off' } }] }], fx.store)
  const chunks = await collect(p.adapter.stream({ provider: 'vox', model: 'voxtral-chat', system: 'You are a helpful assistant.', messages: [user(fx.handle('jfk.wav'), 'What does the speaker ask?')] }))
  assert.equal(server.calls.length, 1, 'no failed first attempt')
  const sent = server.calls[0].json.messages
  assert.equal(sent.some(m => m.role === 'system'), false)
  assert.match(sent[0].content.find(c => c.type === 'text').text, /^You are a helpful assistant\.\n\n/)
  assert.ok(chunks.some(c => c.type === 'block-end'))
  const log = (await readLog()).at(-1)
  assert.deepEqual([log.request.systemPlacement, log.request.systemPlacementReason], ['user-prefix', 'model-rule:voxtral-mini-3b-2507'])
})

test('auto on an unlisted model: one retry on the exact server rejection, remembered per deployment; explicit settings win; other 400s never retry', async (tc) => {
  const server = await mistralLikeChat()
  tc.after(() => server.close())
  const fx = await multiStore([[wav(0.5), 'clip.wav']])
  const route = models => [{ provider: 'm', displayName: 'M', baseURL: server.url, models }]
  const ask = (p, model) => collect(p.adapter.stream({ provider: 'm', model, system: 'Be brief.', messages: [user(fx.handle('clip.wav'), 'Summarize.')] }))

  const auto = await plugin(route([{ id: 'small', upstreamModel: 'mistralai/Voxtral-Small-24B-2507', streaming: { text: 'off' } }]), fx.store)
  await ask(auto.p, 'small')
  assert.deepEqual(server.calls.map(c => c.json.messages.some(m => m.role === 'system')), [true, false], 'system first, then folded retry')
  let log = (await auto.readLog()).at(-1)
  assert.deepEqual([log.request.systemPlacementReason, log.retriedWithUserPrefix], ['server-rejected-system-with-audio', true])
  await ask(auto.p, 'small')
  assert.equal(server.calls.length, 3, 'second request goes straight to user-prefix')
  log = (await auto.readLog()).at(-1)
  assert.equal(log.request.systemPlacementReason, 'observed:server-rejected-system-with-audio')

  server.calls.length = 0
  const explicit = await plugin(route([{ id: 'vox-sys', upstreamModel: 'mistralai/Voxtral-Mini-3B-2507', systemPromptWithAudio: 'system', streaming: { text: 'off' } }]), fx.store)
  await assert.rejects(ask(explicit.p, 'vox-sys'), e => e.code === 'INVALID_REQUEST' && /tokenizer version 13/.test(e.message) && /systemPromptWithAudio: "user-prefix"/.test(e.message))
  assert.equal(server.calls.length, 1, 'explicit system is honored: no silent retry')

  server.calls.length = 0
  const prefix = await plugin(route([{ id: 'generic', upstreamModel: 'org/any-audio-llm', systemPromptWithAudio: 'user-prefix', streaming: { text: 'off' } }]), fx.store)
  await ask(prefix.p, 'generic')
  assert.equal(server.calls[0].json.messages.some(m => m.role === 'system'), false)
  assert.equal((await prefix.readLog()).at(-1).request.systemPlacementReason, 'config')

  // Not a global policy: other models keep the system message; text-only requests keep it even on Voxtral.
  server.calls.length = 0
  const other = await plugin(route([{ id: 'qwen', upstreamModel: 'Qwen/Qwen2-Audio-7B-Instruct', streaming: { text: 'off' } }, { id: 'vox', upstreamModel: 'mistralai/Voxtral-Mini-3B-2507', streaming: { text: 'off' } }]), fx.store)
  await collect(other.p.adapter.stream({ provider: 'm', model: 'vox', system: 'Be brief.', messages: [user('No audio here.')] }))
  assert.equal(server.calls[0].json.messages[0].role, 'system')

  const accepting = await scriptedServer(async (req, res) => { res.writeHead(200, { 'content-type': 'application/json' }); res.end(JSON.stringify({ choices: [{ index: 0, message: { content: 'ok' }, finish_reason: 'stop' }] })) })
  tc.after(() => accepting.close())
  const qwen = await plugin([{ provider: 'm', displayName: 'M', baseURL: accepting.url, models: [{ id: 'qwen', upstreamModel: 'Qwen/Qwen2-Audio-7B-Instruct', streaming: { text: 'off' } }] }], fx.store)
  await ask(qwen.p, 'qwen')
  assert.deepEqual([accepting.calls[0].json.messages[0].role, (await qwen.readLog()).at(-1).request.systemPlacementReason], ['system', 'auto:default'], 'audio + system stays a system message for other models')

  const plain400 = await scriptedServer(async (req, res) => { res.writeHead(400, { 'content-type': 'application/json' }); res.end('{"error":{"message":"max_tokens is too large"}}') })
  tc.after(() => plain400.close())
  const p4 = await plugin([{ provider: 'm', displayName: 'M', baseURL: plain400.url, models: [{ id: 'x', upstreamModel: 'org/x', streaming: { text: 'off' } }] }], fx.store)
  await assert.rejects(ask(p4.p, 'x'), /max_tokens/)
  assert.equal(plain400.calls.length, 1)
  // Settings/row configs that never mention it resolve to auto.
  assert.equal(resolveConfig({ routes: route([{ id: 'z' }]) }).routes[0].models[0].systemPromptWithAudio, 'auto')
})

test('Harness "[model changed: …]" notice after the prompt: transcribe and speech text/options/reference read the pending turn', async (tc) => {
  const asr = await scriptedServer(async (req, res) => { res.writeHead(200, { 'content-type': 'application/json' }); res.end('{"text":"ask not what your country can do for you"}') })
  tc.after(() => asr.close())
  const header = wavHeader({ encoding: 'pcm_s16le', sampleRate: 24000, channels: 1 }, 2400)
  const tts = await scriptedServer(async (req, res) => { res.writeHead(200, { 'content-type': 'audio/wav' }); res.end(Buffer.concat([header, pcm16(0.05, 24000)])) })
  tc.after(() => tts.close())
  const fx = await multiStore([[wav(0.4, 16000, 300), 'question.wav'], [wav(0.3, 16000, 900), 'reference-voice-1.wav']])
  const { p } = await plugin([
    { provider: 'a', displayName: 'A', baseURL: asr.url, models: [{ id: 'asr', mode: 'transcribe', streaming: { text: 'off' } }] },
    { provider: 't', displayName: 'T', baseURL: tts.url, models: [{ id: 'clone', mode: 'speech', streaming: { audio: 'off' }, speech: { refAudio: 'attachment' } }] },
  ], fx.store)
  const notice = modelChanged('voxtral-chat', 'asr')

  await collect(p.adapter.stream({ provider: 'a', model: 'asr', messages: [user(fx.handle('question.wav'), 'Transcribe this.'), notice] }))
  assert.equal(asr.calls.length, 1, 'transcribed despite the trailing notice (0.4.1: NO_AUDIO_INPUT)')

  await collect(p.adapter.stream({ provider: 't', model: 'clone', messages: [user(fx.handle('reference-voice-1.wav'), `${optionsBlock({ v: 1, voice: 'ryan', referenceAudio: 'reference-voice-1.wav' })}\nSay hello to the museum visitors.`), notice] }))
  const body = tts.calls[0].json
  assert.equal(body.input, 'Say hello to the museum visitors.', 'speaks the prompt, not the notice')
  assert.equal(body.voice, 'ryan', 'options block of the prompt still applies')
  assert.ok(body.ref_audio.startsWith('data:audio/wav;base64,'))

  // Same notice without a source tag (e.g. restored history) is recognized by its exact text.
  await collect(p.adapter.stream({ provider: 't', model: 'clone', messages: [user('Second line to read.'), user('[model changed: assistant turns above this point were generated by a; the session continues with clone]')] }))
  assert.equal(tts.calls[1].json.input, 'Second line to read.')

  // Audio before the last assistant message is not the pending turn.
  await assert.rejects(collect(p.adapter.stream({ provider: 'a', model: 'asr', messages: [user(fx.handle('question.wav')), { role: 'assistant', content: [text('done')] }, user('and now?'), notice] })), e => e.code === 'NO_AUDIO_INPUT')
})

test('catalog adapter_models `wire`: realtime wire from the top-level field; mismatches and unimplemented wires fail clearly', async () => {
  const base = models => ({ routes: [{ provider: 'c', displayName: 'C', baseURL: 'http://127.0.0.1:9/v1', models }] })
  const tts = resolveConfig(base([{ id: 'voxcpm2-ws', upstreamModel: 'openbmb/VoxCPM2', mode: 'realtime', wire: 'omni-speech-ws', realtime: { outputSampleRate: 48000 } }])).routes[0].models[0]
  assert.deepEqual([tts.realtime.wire, tts.realtime.path, tts.realtime.outputSampleRate, tts.realtime.outputSampleRateExplicit], ['omni-speech-ws', '/audio/speech/stream', 48000, true])
  // Voxtral chat entry from catalog 1.0.0-full-census.202609150329 (validatedOn trimmed): accepted verbatim.
  const vox = resolveConfig(base([{ upstreamModel: 'mistralai/Voxtral-Mini-3B-2507', catalogId: 'vllm:mistralai/Voxtral-Mini-3B-2507', revision: '3060fe34b35ba5d44202ce9ff3c097642914f8f3', deploymentId: 'a3-vllm-voxtral-mini-3b-2507', generated: true, review: 'validated', id: 'voxtral-mini-3b-2507-chat', tasks: ['audio.understand'], mode: 'chat', wire: 'openai-chat-audio', streaming: { text: 'sse' }, systemPromptWithAudio: 'user-prefix' }])).routes[0].models[0]
  assert.deepEqual([vox.mode, vox.systemPromptWithAudio, vox.deploymentId], ['chat', 'user-prefix', 'a3-vllm-voxtral-mini-3b-2507'])
  const { catalogTasksOf, catalogTasksSourceOf } = await import('../src/task-map.js')
  assert.deepEqual([catalogTasksOf(vox), catalogTasksSourceOf(vox)], [['audio_understanding_qa', 'spoken_chat_text_reply'], 'derived'], 'derived tasks are labeled: they may over-claim for a row')
  assert.equal(catalogTasksSourceOf({ ...vox, catalogTasks: ['audio_understanding_qa'] }), 'config')
  // Unvalidated catalog entries carry deploymentId: null (and other nulls); they must not refuse the whole route.
  const unvalidated = resolveConfig(base([{ id: 'qwen3-asr', upstreamModel: 'Qwen/Qwen3-ASR-0.6B', mode: 'transcribe', wire: 'openai-transcriptions', deploymentId: null, revision: 'abc', review: 'needs-review', asr: { responseFormat: 'json' } }])).routes[0].models[0]
  assert.equal('deploymentId' in unvalidated, false)
  assert.throws(() => resolveConfig(base([{ id: 'x', mode: 'chat', wire: 'omni-speech-ws' }])), /wire "omni-speech-ws" needs mode "realtime"/)
  assert.throws(() => resolveConfig(base([{ id: 'x', mode: 'realtime', wire: 'vllm-asr', realtime: { wire: 'omni-turn' } }])), /conflicts with realtime.wire/)
  assert.throws(() => resolveConfig(base([{ id: 'x', mode: 'chat', wire: 'omni-realtime-video' }])), /not implemented by this adapter/)
})

test('per-turn speech fields of /v1/audio/speech: speed/seed/sample_rate/extra_params/ambient_sound/duration, ref_audio list, ref_audio_2, emotion clip, word_timestamps', async (tc) => {
  const header = wavHeader({ encoding: 'pcm_s16le', sampleRate: 24000, channels: 1 }, 4800)
  const server = await scriptedServer(async (req, res, call) => {
    const headers = { 'content-type': 'audio/wav' }
    if (call.json.word_timestamps) headers['x-word-timestamps'] = JSON.stringify([{ word: 'Hello', start_ms: 0, end_ms: 320 }, { word: 'world', start_ms: 340, end_ms: 700 }])
    res.writeHead(200, headers)
    res.end(Buffer.concat([header, pcm16(0.1, 24000)]))
  })
  tc.after(() => server.close())
  const fx = await multiStore([[wav(0.2, 16000, 200), 'speaker-a.wav'], [wav(0.2, 16000, 500), 'speaker-b.wav'], [wav(0.2, 16000, 800), 'angry.wav']])
  const { p, readLog } = await plugin([{ provider: 's', displayName: 'S', baseURL: server.url, models: [
    { id: 'ttsd', mode: 'speech', streaming: { audio: 'auto' }, speech: { refAudio: 'attachment' } },
    { id: 'sfx', mode: 'speech', streaming: { audio: 'off' } },
  ] }], fx.store)
  const run = (model, blocks) => collect(p.adapter.stream({ provider: 's', model, sessionId: 's', messages: [user(...blocks)] }))

  await run('ttsd', [fx.handle('speaker-a.wav'), fx.handle('speaker-b.wav'), fx.handle('angry.wav'),
    `${optionsBlock({ v: 1, speed: 1.25, seed: 7, sampleRate: 24000, extraParams: { emo_alpha: 0.6, lang: 'en' }, referenceAudio: 'speaker-a.wav', referenceAudio2: 'speaker-b.wav', emotionAudio: 'angry.wav', wordTimestamps: true })}\n[S1] Hello [S2] world`])
  const b = server.calls[0].json
  assert.deepEqual([b.speed, b.seed, b.sample_rate, b.word_timestamps, b.input], [1.25, 7, 24000, true, '[S1] Hello [S2] world'])
  assert.equal(b.stream, undefined, 'word_timestamps forces a non-streaming request (server rejects it with stream=true)')
  assert.deepEqual([b.extra_params.emo_alpha, b.extra_params.lang], [0.6, 'en'])
  const decode = d => Buffer.from(d.split(',')[1], 'base64')
  assert.ok(decode(b.ref_audio).equals(wav(0.2, 16000, 200)))
  assert.ok(decode(b.ref_audio_2).equals(wav(0.2, 16000, 500)))
  assert.ok(decode(b.extra_params.emo_audio).equals(wav(0.2, 16000, 800)))
  const log = (await readLog()).at(-1)
  assert.equal(typeof log.request.body.ref_audio_2.sha256, 'string', 'clips are logged by hash, not inlined')
  assert.deepEqual(log.request.body.extra_params.emo_audio.name, 'angry.wav')

  // Ming-omni-tts podcast mode: ref_audio as a list of clips.
  await run('ttsd', [fx.handle('speaker-a.wav'), fx.handle('speaker-b.wav'), `${optionsBlock({ v: 1, referenceAudio: ['speaker-a.wav', 'speaker-b.wav'], referenceText: 'a|b', xVectorOnlyMode: false })}\nTwo hosts talk.`])
  assert.equal(Array.isArray(server.calls[1].json.ref_audio) && server.calls[1].json.ref_audio.length, 2)
  assert.equal(server.calls[1].json.x_vector_only_mode, false)

  // MOSS-SoundEffect: description in ambient_sound, empty input allowed.
  await run('sfx', [optionsBlock({ v: 1, ambientSound: 'ocean waves on a rocky beach', durationSeconds: 5 })])
  assert.deepEqual([server.calls[2].json.input, server.calls[2].json.ambient_sound, server.calls[2].json.duration_seconds], ['', 'ocean waves on a rocky beach', 5])

  // Word timestamps surface in the result block.
  const chunks = await run('ttsd', [fx.handle('speaker-a.wav'), `${optionsBlock({ v: 1, wordTimestamps: true })}\nHello world`])
  const final = chunks.filter(c => c.type === 'block-end').map(c => c.block.text).join('\n')
  const id = /\/api\/dsh-dgx-audio\/v1\/result\?id=([A-Za-z0-9._~-]+)\)/.exec(final)[1] // 0.4.3 link-line carrier
  const result = await (await p.routes().find(r => r.path.endsWith('/result')).fetch(new Request(`http://h/api/dsh-dgx-audio/v1/result?id=${id}`))).json()
  assert.deepEqual(result.wordTimestamps, { state: 'aligned', words: [{ word: 'Hello', startMs: 0, endMs: 320 }, { word: 'world', startMs: 340, endMs: 700 }] })

  await assert.rejects(run('sfx', [`${optionsBlock({ speed: 0.1 })}\nx`]), e => e.code === 'INVALID_REQUEST' && /speed/.test(e.message))
  await assert.rejects(run('sfx', [`${optionsBlock({ seed: 1.5 })}\nx`]), /seed/)
  await assert.rejects(run('sfx', [`${optionsBlock({ referenceAudio2: 'missing.wav' })}\nx`]), /not part of this message/)
  const doc = p.routes().find(r => r.path.endsWith('/capabilities'))
  const params = (await (await doc.fetch(new Request('http://h/api/dsh-dgx-audio/v1/capabilities'))).json()).routes[0].models[0].params
  assert.deepEqual(params.find(x => x.key === 'speed'), { key: 'speed', type: 'number', min: 0.25, max: 4 })
  assert.deepEqual(params.find(x => x.key === 'seed'), { key: 'seed', type: 'number', step: 1 })
  assert.equal(params.find(x => x.key === 'voice').source, 'voices')
})

test('speech stream-input: per-chunk sample_rate wins over the nominal audio.start 24000; binary frames use an explicit configured rate', async (tc) => {
  const server = await wsServer((conn) => {
    conn.onMessage(async (m) => {
      if (m.type !== 'input.done') return
      conn.send({ type: 'audio.start', utterance_index: 0, sentence_index: 0, sentence_text: 'Hi.', format: 'pcm', sample_rate: 24000 })
      if (conn.url.pathname.includes('json')) {
        conn.send({ type: 'audio.chunk', utterance_index: 0, sentence_index: 0, chunk_id: 0, sample_rate: 48000, audio_b64: pcm16(0.1, 48000).toString('base64'), timestamps: null })
      } else {
        conn.sendBinary(pcm16(0.1, 22050))
      }
      await sleep(50)
      conn.send({ type: 'audio.done', utterance_index: 0, sentence_index: 0 })
      conn.send({ type: 'session.done', utterance_index: 0, total_sentences: 1 })
    })
  })
  tc.after(() => server.close())
  const outputDir = await tempDir('dgx-042-ws-')
  const p = createAudioPlugin({ rowConfig: { outputDir, hubLimits: { pingMs: 60_000 }, routes: [{ provider: 'w', displayName: 'W', baseURL: server.baseURL, models: [
    { id: 'json48k', mode: 'realtime', realtime: { wire: 'omni-speech-ws', path: '/json/audio/speech/stream' } },
    { id: 'bin22k', mode: 'realtime', realtime: { wire: 'omni-speech-ws', outputSampleRate: 22050 } },
  ] }] }, log: () => {} })
  const events = []
  const ac = new AbortController()
  const reading = (async () => { try { for await (const e of p.hub.subscribe('s', { signal: ac.signal })) events.push(e) } catch { /* aborted */ } })()
  const post = async (path, body) => (await p.routes().find(r => r.path === path.split('?')[0]).fetch(new Request(`http://h${path}`, { method: 'POST', body: JSON.stringify(body) }))).json()
  for (const model of ['json48k', 'bin22k']) {
    const opened = await post('/api/dsh-dgx-audio/v1/live/open', { sessionId: 's', provider: 'w', model })
    await post(`/api/dsh-dgx-audio/v1/live/text?liveId=${opened.liveId}`, { text: 'Hi.', done: true })
    await sleep(250)
    await post(`/api/dsh-dgx-audio/v1/live/close?liveId=${opened.liveId}`, {})
  }
  ac.abort()
  await reading
  const rates = events.filter(e => e.type === 'audio.format').map(e => e.sampleRate)
  assert.deepEqual(rates, [48000, 22050])
  const ends = events.filter(e => e.type === 'audio.end')
  assert.deepEqual(ends.map(e => e.totalSamples), [4800, 2205])
  p.dispose()
})
