// 0.4.8 (TASK_CONTRACT §K.14): focused two-model demo. A MiMo-Audio spoken-dialogue chat entry receives the shared mic
// WAV as the only content of its user turn (no Harness "[model changed: …]" notice turn), the entry's recipe system
// prompt, and its extraBody sampling_params_list verbatim; the sampling fields actually sent are logged. Mock transport only:
// the sampling values below are test fixtures, not the DGX recipe.
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { test } from 'node:test'
import { createUserMessage, fileHandleText } from '@deepseek-ai/dsh-llm'

import { createAudioPlugin } from '../src/index.js'
import { collect, omni, pcm16, scriptedServer, tempDir, wav, wavFromPcm, writeSse } from './helpers/fixtures.js'

const text = t => ({ type: 'text', text: t })
const user = (...blocks) => ({ role: 'user', content: blocks.map(b => (typeof b === 'string' ? text(b) : b)) })
const assistant = t => ({ role: 'assistant', content: [text(t)] })
// Exactly what dsh-agent model-selection appends after the prompt on the first request after a switch.
const modelChanged = (from, to) => createUserMessage({
  content: [text(`[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`)],
  source: { kind: 'plugin', plugin: 'model-selection', form: 'notice', summary: { text: `${from} → ${to}` } },
})

const FIXTURE_SAMPLING = [
  { temperature: 0.0, top_p: 1.0, top_k: -1, max_tokens: 3200, seed: 42, detokenize: true, repetition_penalty: 1.1 },
  { temperature: 0.0, top_p: 1.0, top_k: -1, max_tokens: 65536, seed: 42, detokenize: true, repetition_penalty: 1.1 },
]
const mimoEntry = (extra = {}) => ({
  id: 'mimo-audio-7b-instruct-s2s', upstreamModel: 'XiaomiMiMo/MiMo-Audio-7B-Instruct', mode: 'chat',
  outputAudio: true, sendModalities: true, systemPrompt: 'You are a helpful assistant.', systemPromptWithAudio: 'system',
  extraBody: { sampling_params_list: FIXTURE_SAMPLING }, ...extra,
})

async function micStore() {
  const { fakeStore } = await import('./helpers/fixtures.js')
  // The mic plugin's recording: WAV PCM s16le mono 16 kHz named recording-YYYYMMDD-HHMMSS.wav.
  const bytes = wav(0.6, 16000, 330)
  const fx = await fakeStore(bytes, 'recording-20260915-110203.wav')
  return { bytes, fx, handle: text(fileHandleText(fx.ref, fx.path)) }
}

async function plugin(routes, store) {
  const outputDir = await tempDir('dgx-048-')
  const p = createAudioPlugin({ rowConfig: { outputDir, hubLimits: { pingMs: 60_000 }, routes }, log: () => {}, attachments: () => store })
  const readLog = async () => (await readFile(p.config().invocationLog, 'utf8')).trim().split('\n').map(l => JSON.parse(l))
  return { p, readLog }
}

function spokenReplyServer() {
  const parts = [pcm16(0.2, 24000, 300), pcm16(0.2, 24000, 500)]
  return scriptedServer(async (req, res) => {
    await writeSse(res, [omni.role(), omni.text('今天天气不错。'), ...parts.map((p, i) => omni.audio(wavFromPcm(p, 24000), i === 1 ? 'stop' : null)), omni.usage(), '[DONE]'], { delayMs: 200 })
  })
}

test('MiMo spoken dialogue: mic WAV after a model switch → user turn is the audio only, recipe system prompt, sampling_params_list verbatim, 24 kHz reply recorded', async (tc) => {
  const server = await spokenReplyServer()
  tc.after(() => server.close())
  const mic = await micStore()
  const { p, readLog } = await plugin([{ provider: 'dgx', displayName: 'DGX', baseURL: server.url, models: [mimoEntry()] }], mic.fx.store)

  const chunks = await collect(p.adapter.stream({
    provider: 'dgx', model: 'mimo-audio-7b-instruct-s2s', sessionId: 'sess-mimo',
    system: 'You are DeepSeek Harness. Follow the workspace rules…',
    messages: [user('hi'), assistant('Hello from MiniCPM'), user(mic.handle), modelChanged('minicpm-o-4-5-s2s', 'mimo-audio-7b-instruct-s2s')],
  }))

  assert.equal(server.calls.length, 1)
  const body = server.calls[0].json
  assert.equal(body.model, 'XiaomiMiMo/MiMo-Audio-7B-Instruct')
  assert.equal(body.stream, true)
  assert.deepEqual(body.modalities, ['text', 'audio'])
  assert.deepEqual(body.messages, [
    { role: 'system', content: [{ type: 'text', text: 'You are a helpful assistant.' }] },
    { role: 'user', content: [{ type: 'text', text: 'hi' }] },
    { role: 'assistant', content: 'Hello from MiniCPM' },
    { role: 'user', content: [{ type: 'input_audio', input_audio: { data: mic.bytes.toString('base64'), format: 'wav' } }] },
  ], 'no notice turn after the audio; the Harness system prompt is replaced by the entry systemPrompt, not folded into the user turn')
  assert.deepEqual(body.sampling_params_list, FIXTURE_SAMPLING, 'stage list sent verbatim')
  assert.equal('temperature' in body, false, 'no top-level sampling field competes with the stage list')
  assert.equal('max_tokens' in body, false)

  const [log] = await readLog()
  assert.equal(log.record, 'invocation')
  assert.equal(log.request.droppedContextNotices, 1)
  assert.equal(log.request.systemPlacement, 'system')
  assert.equal(log.request.systemPrompt, 'You are a helpful assistant.')
  assert.deepEqual(log.request.sampling.sampling_params_list, FIXTURE_SAMPLING)
  assert.deepEqual([log.request.sampling.temperature, log.request.sampling.max_tokens], [null, null])
  assert.deepEqual(log.request.sampling.extraBodyKeys, ['sampling_params_list'])
  assert.match(log.request.sampling.extraBodySha256, /^[0-9a-f]{64}$/)
  assert.deepEqual(log.request.messages.map(m => m.role), ['system', 'user', 'assistant', 'user'])
  assert.deepEqual([log.inputAudio[0].name, log.inputAudio[0].sampleRate, log.inputAudio[0].channels, log.inputAudio[0].sha256], ['recording-20260915-110203.wav', 16000, 1, mic.fx.digest])
  assert.equal(log.outputAudio.delivery, 'progressive')
  assert.equal(log.outputAudio.chunks, 2)
  assert.equal(log.outputAudio.durationSeconds, 0.4)
  const reply = chunks.find(c => c.type === 'block-end').block.text
  assert.match(reply, /^今天天气不错。/)
  assert.match(reply, /\/api\/dsh-dgx-audio\/v1\/recording\?id=/)
})

test('context notices are dropped wherever they sit in the history; auxiliary calls are unchanged', async (tc) => {
  const server = await spokenReplyServer()
  tc.after(() => server.close())
  const mic = await micStore()
  const { p, readLog } = await plugin([{ provider: 'dgx', displayName: 'DGX', baseURL: server.url, models: [mimoEntry()] }], mic.fx.store)
  const restoredNotice = user('[model changed: assistant turns above this point were generated by a; the session continues with b]')

  await collect(p.adapter.stream({
    provider: 'dgx', model: 'mimo-audio-7b-instruct-s2s', sessionId: 'sess-2',
    messages: [user('earlier'), modelChanged('x', 'y'), assistant('ok'), restoredNotice, user(mic.handle)],
  }))
  const roles = server.calls[0].json.messages.map(m => m.role)
  assert.deepEqual(roles, ['system', 'user', 'assistant', 'user'])
  assert.equal(JSON.stringify(server.calls[0].json.messages).includes('[model changed'), false)
  assert.equal((await readLog())[0].request.droppedContextNotices, 2)

  // Auxiliary call (compaction) on a chat model: text-only request, no speech, messages as in 0.4.7 (notice kept).
  await collect(p.adapter.stream({ provider: 'dgx', model: 'mimo-audio-7b-instruct-s2s', purpose: 'compaction', messages: [user('earlier'), modelChanged('x', 'y')] }))
  const aux = server.calls[1].json
  assert.deepEqual(aux.modalities, ['text'])
  assert.equal(JSON.stringify(aux.messages).includes('input_audio'), false)
  assert.equal(JSON.stringify(aux.messages).includes('[model changed'), true, 'auxiliary conversion unchanged')
  assert.equal((await readLog())[1].request.droppedContextNotices, 0)
})

test('sampling record: entries without extraBody log nulls; top-level temperature / max_tokens are logged when sent', async (tc) => {
  const server = await spokenReplyServer()
  tc.after(() => server.close())
  const mic = await micStore()
  const { p, readLog } = await plugin([{ provider: 'dgx', displayName: 'DGX', baseURL: server.url, models: [
    { id: 'minicpm-o-4-5-s2s', mode: 'chat', outputAudio: true, sendModalities: true, temperature: 0.3, maxTokens: 512 },
  ] }], mic.fx.store)
  await collect(p.adapter.stream({ provider: 'dgx', model: 'minicpm-o-4-5-s2s', sessionId: 's3', messages: [user(mic.handle)] }))
  const body = server.calls[0].json
  assert.deepEqual([body.temperature, body.max_tokens, 'sampling_params_list' in body], [0.3, 512, false])
  const [log] = await readLog()
  assert.deepEqual(log.request.sampling, { temperature: 0.3, max_tokens: 512, sampling_params_list: null, extraBodyKeys: [], extraBodySha256: null })
  assert.equal(log.request.droppedContextNotices, 0)
})
